language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: M1nLdH2mmRd8lBI0zaas8rOZ8GdfH01ErrkP702Fr0PB+aztdivcRum/HuGuvQRdBvSk9ZvuJ16JzfMT4OdzFhBTT7KozptMVmMILTWbhc57iYJlOOFYO5gXMEXKy9qGi/xHlc3VMwXGfCJScyZtOUV5ilXjQ7XelPHtDtyYrYOuoAIbghcE2+nMmcPSuVFdMhBEddAQC0vRjT6EKVfwwDkBpnOwcEBKK4A7gpFczL+Q0umd+pR/WTyIyRoekGL7eUzghRJAzHvmHRfuHRVvg0oKKU/8nYFXhI2rIIut48oHTBibaOcXFRLzKd+j4kyJcEwApPYyuCJgrVPsnvRvG81vG4Kl+6jEhBYR86jX3HPH5xGXXP9JEjfeBuHFZGjT+BPa5CQMoAECxVDN/b8M3+YDUIeI3xmhii6fQEH/NDkuG8QVQ0zO1BVN/R1WBhyFk71HkzKkQlJnkN6XwY96HayEqP/O3umnzpjqrr+gOb0s3PAQvnyzQQS5myTlkBGZPv3mrcMDVFmsxRu906BT1RbD6JmO4aNktz8UQFifE6ONSsZxMAwlzdr1avAjmS5bsZCwY9AgV94EEvT9ZDtQnZRR4mWNM9NpHJaRCCKozKTJeUY3L+Om0eQlELXmBgeI4t9DRwS1fv64bUWieEVIfn86CzNeHq4xqVjk5lWQDww=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: LtDbEh5ld2zhgK8gPvz2+xudyaHFJ0xgrkFtWFBlPP9FzM3OvmlUb21r5kMHe7da4L/f1L1rIB03X0ZaIfxA9UmTYxdAVDAaNyq//T7XYUZn3ZfojbAenbAPMherPK+Xf0cquGppWevaueFzE/LvfB0u+L+z6II/+OgoZwVUhkA7u1NVU2Mo9P5hGkG0wJKHyDHIkAlH/pQV06+wi8dlnG6oE6c6cFnqwF38dwwwkF5IcKo3K5L7WAX/h/kgA/ogUk8Dvngrd7PtHRV6fP0Rg5WM8AsqYs4IK+tKkIPVM7NdOkXE3kOqZaPXnhaf99dJv2c0M846tpJtwXW0iTXa2nv6C1Q5VIU9XeGPo/F3R01VNk/Ajb8P2oyKRYcnO5r/7crY5T2cq3cEnX9zIP8OqGJ4wMhGOA/OZhMFBLd+wp65b5gXgkdAO8ILECYscCurSrtaLfUhSDYDIb7QVwVhMeJiwhsSya5ZXCoKpnH3Bib7Zxi60pkytzfUcHPhdK7bOWc9DkAETW/NTiQwojNdPRnZ2l2WINQl+34Irgh3ZTKxOT/dWWFNcwLOuhDnbZeL05Xf1wYnsL76Ad1ZIlKSm+V6QORafsIEjDUrrVAmvOVukGCkmteHkTeSlUxF9t7m28KKcndcCkueG+4Jwfmk5COKFOoYmyV9h9zh/5m3hgE=
  - secure: XUiGxnXYmcrE61fZLQeWrwRDwLsKJ/KEWpJoIaZsfqX/HSYXctZEqz1p10re2Do0d0QZrvyg84ey9oQMOKABl4kjtnPoQxh3zvFY5N7yRz0bGTfCN6/B+v779YrUWfugCRUFZp63ysZy/9C9vSNc5CLml7ETGf14subONvnE1pTpU9dpEjMsB5o7+E8wleI2drxq1YnRL092XvTT5EjhoV+0fYww1ssSSePqn8GFvIpOa1I+y9IbpETmKfZxrcfnqGaalX2nRk5AuaaKNeYX3luH30owEfQxLiyU1dmiqChFPuMgK3dNOtFJ6d4CfRuXk/9xDRLNTqFzqQjkF0wYHxRjR4IVaozqN47La935WttSwFq3KmFb1PSqUW8bw+NMLcG8B5oxkbcfRm3gdl0Ebtg7WVSLIuBOv+W5kyhTwnhxoVGwz4yr2kEO8xG9DJwP+61a9gDmJeNmQpijNSf8k9WeBM+HMZbAwIDmiaVEpujVlCEhfwJTzABaKSpqvMxpPVWqxueI5AFQ3dJLKf55+m/w3XCJYrVobDJQOAV/jfZdtgYmvfbAtqXqCO8isx2DIy16dGWj5JKXzHCXpeLZsMA7N6kciMTYtGLtMs3f9IZRJVe4S9Fwjk3lCLlyvnhTpcSmXLoyRqri2Qc1KRzR3gHt/wbVLXbUR/63zFAnF0s=
  - secure: aNw/i5r9b3LgaBfMeQ3/NbF5E25YDdxRuwCstlBRwI4EAGyUBjftJqF0r2bm+95Ingm3xTLv7Ia01/CRiA9UUWQFfkWTp3e+lWp5t8PNbroqw+504Te7XfBU1Bq1qQQh2WjztMqBPuVuXwYR9DBa1YZtED2Ubqt/nsHVrJzJ6vJR8kKPHyv6C5eblqKUC7FXk/vG2uV/LyE5D3U629xMwhV+fejv3spr2+Yvjj3XUkbNW7qLSFz2P2MjZVIasOtg7zWckwAQnB4ZxMgZ9ear9dqzLalX/BKR0TlrkCJb+pTq2ucjQ3rTpXCg49+3qcDAO5lRs8dak2LQJHyrEHiR25hxufVg8VHBlb3oUvYvKYTRxYO3faRtm1PgtlgdKiOM84QEaffhoDMwWw6jJy8iOQ6uxvTko1vLJutDAeb7tjhYkixCjSG1UdOco1MHmdLgxLfqY5ko8OA3TDUQHQqrRGV9fWPsdlzXP59lfNaJIE/0nK30n/7fYJYk+NwRz1oPFqnXqfMWOEcA47ldDrPzr2EVGcSJWf3zj3UbQwS73X5P6nzUYADF/eT+d+uGxq7N8r+HByaGS3kh88JP8Zo1fD+j4Ue98h2nhJpcJ9A/pUqHkVhZn0Vq6j1Qdm5EqCGehUb4MQZhevBAxlG5bNcYjte71FUL2Z9aKl8v0IZZ26Q=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
