language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: M1nLdH2mmRd8lBI0zaas8rOZ8GdfH01ErrkP702Fr0PB+aztdivcRum/HuGuvQRdBvSk9ZvuJ16JzfMT4OdzFhBTT7KozptMVmMILTWbhc57iYJlOOFYO5gXMEXKy9qGi/xHlc3VMwXGfCJScyZtOUV5ilXjQ7XelPHtDtyYrYOuoAIbghcE2+nMmcPSuVFdMhBEddAQC0vRjT6EKVfwwDkBpnOwcEBKK4A7gpFczL+Q0umd+pR/WTyIyRoekGL7eUzghRJAzHvmHRfuHRVvg0oKKU/8nYFXhI2rIIut48oHTBibaOcXFRLzKd+j4kyJcEwApPYyuCJgrVPsnvRvG81vG4Kl+6jEhBYR86jX3HPH5xGXXP9JEjfeBuHFZGjT+BPa5CQMoAECxVDN/b8M3+YDUIeI3xmhii6fQEH/NDkuG8QVQ0zO1BVN/R1WBhyFk71HkzKkQlJnkN6XwY96HayEqP/O3umnzpjqrr+gOb0s3PAQvnyzQQS5myTlkBGZPv3mrcMDVFmsxRu906BT1RbD6JmO4aNktz8UQFifE6ONSsZxMAwlzdr1avAjmS5bsZCwY9AgV94EEvT9ZDtQnZRR4mWNM9NpHJaRCCKozKTJeUY3L+Om0eQlELXmBgeI4t9DRwS1fv64bUWieEVIfn86CzNeHq4xqVjk5lWQDww=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: NGLBAiM9F9LZZ5Ph4RlRBC/DjCXXXhtxpuIUKhYDVLYAxZDjutBXpKYvJXzwEGLSeisVs87fEE2zImq2r+ZHz16IF+UZS9CT8pvn7Ui8QYtz5aQ8jsgmVI4g6YiA6mFrIgufZsstBYmXk6ycyUhfNNp/Nd0UAHfuf3cXHwpotrU1kQhC6OdPbnou+n1HvkTvKJ2ZzEdmOfJic2e3RHQyjqtqeEHgG1qvN9UwW0DnSb5ew1ejeNXUk0Y23xXlM5Vna366IIaWe08FUMk03ZbzHxsZ0Zf3j+rjXHxYXoufwvrROpVVp8Eg0jODV5hXAu1aQFH4d4xsZf8PblNBOBDETQrSpNfcYe/BVIclT/8+SaNF2I/PfZLokDWNv8dNL2vKb3SWUyaS3IR/yBxiQjeK6veRr7BjzzCa9GQ1YVfMmtr9IiQJfPW5p/GUiFLHQwVQ5tyLiAwJVDcaDEl16a+ampaPss5IHtJxCDBL1F5w+Ulq17MsJ1DOVHktWof+E1v6XB6cZB/txRAGOh5bd58OJMAjiDZwrv1LcsjnhcITgDyOguuJEN3w3AJW0jCqI01efQ27xc5Y/QF9BzFNIHotyFFlMoa+mmEKknBkKQ9+cW/VkDNvp53ArSQr231DUHwtULCP/KgIlTCXwydOaprutBSEz2Y3dOFgH5PWWfnD3rk=
  - secure: 9Ye5kuX1SQz80w3di8lfq9+hjLp2jaUyHOgHV7Ew7iMA1aC+CO4jwyRzPOS7R0Y6Dpqe7ZXJgxzdJUeJkFnMZYgMv46hn3zo6t1v1Wyfg4S023Q92PgwITw64dx/4yZH6Y78WDeG46pmabDFyC91hyxQAprq+l8J3BTs4/LsDwHC6PbkpNBYyP4r030/h+kq1HxPQKbHpMvCDeMX7b9t9Ff/JPWz8C+RZgF6Y4fU/b1CwyfkoUI2AYadvQDCle6M1eG8cYvhYFuF2TdLdGKUsSxH9uNkjJIWDhX6c2xqddbmg/BW4Qgv58b+i8cGDd9XdcOM7ZiAbqujfCSIvhqTdDrYmH7aCaIFUcZITAe2OEqHMOo4izkahhYtesM8wSsa6AEkVWANvYqz5za+k0pmaeKHfZAodlpjfI8ErcjK9CwidCy6kmbcKP5ERMJ1sDYde5Wd0eHSv0yNUPRi0i492wnm6QisLUwurOo2WoTMqB9L4Qmd9P2IGqqbWOdQZm8SWiOk9rbktcxiQl9tAi5oJ3BazTAlyH0oaffp8aYAAJ5e4wUNSZ+R9valKP7+djQAknKm5xkcFwOBprw0RBrhwdpiXJsvQFzl2w6DEPzjk1EF0lMJxNpYtJsiZIQUYoaK8dqS3Z52xJt8/KqBlMy4yvAVY/PUYvZ1LaKCYHPNX4w=
  - secure: HoGXQ4VeuM39weLRjh4aicld7nc2SXGMonA+U2FekwbZr/Dpsua1JfT2ihJVwYlm9/5S/A7a9/ta2bipRHXVmWr/N2Q6oEZk6xBJTYh1t3K0eZnwJVR9Wc5NDHUQn2MG3VYIPOmRIVfEqn+c5ovLf2Co4l/LTpT6J0layFIm/XdWK7N6PQ6haxyPmPzYXiUkv2tYhAqoLVBLjwQcpoa3itGNW4XuwEORHFSjSt7naWIyYuLWu2Zx0pWj/fvjD+r9OxEYltP0lf6qNwt6ww1SsajhHy+6mRHLTTF5kyAlIFaDhiFNamT8DXJrWiVPM61hYVXARIomTgsacIcSCTH0UXfRHkyQ0G/YUA/3ax9PLfGe7prvua3YKUFy/ScHBu5xf/xMdwDnLTrzMoEt+c0j1CfVQoab+PyWUx92ZNUtmzKKvwyv2rKVL3ppPTD5HbcJ1fDVG4QlEUc0Q1uYpxag6ocV22WjVFSzhMy0pxPkTTOuFbIn6ve8K7B7c+8hurf8FHi4wfCerfeOCwj0vpHszDgz2xURma1T2cQ9CBkSoYF1hP9YO0GkDX2JLgT5q0NqXWjiuSS+XyH9nbcomlz8eth2/SZKbvgqiB8I1XfkAUo/D0eXQNr+bXr6HW9sL6+n48M8IkoiKqPcRe0TKgKo45tCiItgiESsoTJMg43uC1I=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
