language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: M1nLdH2mmRd8lBI0zaas8rOZ8GdfH01ErrkP702Fr0PB+aztdivcRum/HuGuvQRdBvSk9ZvuJ16JzfMT4OdzFhBTT7KozptMVmMILTWbhc57iYJlOOFYO5gXMEXKy9qGi/xHlc3VMwXGfCJScyZtOUV5ilXjQ7XelPHtDtyYrYOuoAIbghcE2+nMmcPSuVFdMhBEddAQC0vRjT6EKVfwwDkBpnOwcEBKK4A7gpFczL+Q0umd+pR/WTyIyRoekGL7eUzghRJAzHvmHRfuHRVvg0oKKU/8nYFXhI2rIIut48oHTBibaOcXFRLzKd+j4kyJcEwApPYyuCJgrVPsnvRvG81vG4Kl+6jEhBYR86jX3HPH5xGXXP9JEjfeBuHFZGjT+BPa5CQMoAECxVDN/b8M3+YDUIeI3xmhii6fQEH/NDkuG8QVQ0zO1BVN/R1WBhyFk71HkzKkQlJnkN6XwY96HayEqP/O3umnzpjqrr+gOb0s3PAQvnyzQQS5myTlkBGZPv3mrcMDVFmsxRu906BT1RbD6JmO4aNktz8UQFifE6ONSsZxMAwlzdr1avAjmS5bsZCwY9AgV94EEvT9ZDtQnZRR4mWNM9NpHJaRCCKozKTJeUY3L+Om0eQlELXmBgeI4t9DRwS1fv64bUWieEVIfn86CzNeHq4xqVjk5lWQDww=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: lg4Ok9MPmmH7AjvWamA5GJI3BcmWeaSQu8xAXcFSa9bKP3LRjTwshJYF/8CMGl0WyKluaUBJwS6p/c63yLwgaa2jjRiHtgOF+p5G31JjYuRdJsuF+UbddRGtADfgHXV7bgexbhUhjnJwSTrhHkbDD4vZl7JoOklqo4GjGxCMemqc2Xf2VmZBN2H2jCTDVJ0Vjs/LUSMJr6IVFAYi8C32hRD9fpzmqJV9caLhRJn6RHCtraZC8GeCA7xWpP5PRnHM4gJU/rT6FVHl45W0K4FhywI3QJX7J8mOzWOQrrt7A1bGGaUNw9XVpD+cvkgQHe64NhORhWtrt+c4WRd44zJc3jXIT5RTdko7fGba8xcBV9LfeFdfXSywXK2v035rqRcWzSYmATSg1UKBGIvT+sAvP4jCxNjxnoahFKJ9Tfzj6oEdu19EdUmaRM3RKvUFwMnb7/BD9Mjm3NJ1Oy8ucZqzXpWx7F3+k6f0cv/uxmnXfmkGHms/6tCfTfE+Y20mV+MvWokACxkTV/6+DbsOLYy6AFRnkH1+O+77kwFuc7AsMkTgUORAjY3XGvAb3SUi6G71eDEvfnGiORO+4Xzsa7AWgtNqMUXCGsb5IQqK03po4nKrsT2oF8PTt9FKeqRRdabZI4nrRPecAtQGKknaJMv6U5DavOswiB/jz8OBXCxUaHs=
  - secure: DlSBIxTD9WJ9ObUQl9deW9BhTA9L8HExIkXmQ3J19BPlQDdQndaAl39rwcpESk+LLYraDJa/ZEZZNrON5zU8PLeXfaLpx3CNI0v9h7dHVraciLb04z6OFzkcQ6l9nnn8Fq9NwHCpQfyityQOyfJh7L8U74IK5IWZfIyL0Q5bDFcupYaa+//xsgcEO64myDpxXSteqMweZG6FkajjHfpe/7O0Ej/A1d51bw5TYSM0sg/UdY33h2pIio9etYUv7yfDxIIu08JqiTSLMKapS0oA+TP0MRYB9TgP+hRWcSdg12PgdgMR4AWokgC6PlVkl5XtwP69pHb/OQ1YGGOOd/TMBoUwqgjSGexivYW/R9wsFkUtZSbae9WSmMB5YMFB7gZvSYHeWmn9nJMR0IqS78Vi/v56Q6wpci/cnw88/lzyy+5VMhbaAQ/plbAbPjl55pemICK1qJVaicy9ip+n3eltibHD2lBg0SyF99Z6B+YQ5tL52ZXUBtjDGBRJ7gz6m7XN6nHHQTTxo9qzAY0oMZnGfkgcpZ/dgmHDBFJDyHhoT6zCBgl8DVaSvE8GPZw3fSe7g428W0QC28bk5BtNNlTEynK56dervCjRiir2q0bLUbT4ZB7aZdFm3T8ysuu6OsUmO5K0XqI1kfAL454JGO0nUvhzTCHhdneXqK3xskEwFlM=
  - secure: xo76i2YEHJHT4KS8u2KM0VfNHEpVQcS5wsoG355hLUZllkwuXSSQZvyhD5hJ9+tf5kTiF/KcXL+PT2xPDjzr6iW7XISvxSAbYLCvC+Cy2WS+AdztqWgQbuLSOXxo5MA/sqI4+Nnlbfbof1cDNdp31cH71M70Mtz753wh+i0tKgBvkqifEALBEvlWn1bShgXJWN2NlTq1dyvRumyqxPn/F3W4Qf9lGE5UJ100rvEOlDNX5tUND2k91ALKEMj1SS4stONRN3p73KecuNjfOPzWrvZvAR1nlPeyBsV9qhiqREmTYB+SVTxVdjfALqZHTGAxpKNp+jZG4DntbgpiD+MAXBEeuOwpNgEl98iW52OJpVHY6O5RVxkMyGjq4uEwhyZ/OM5DCXKEDm/nrPv6djkf/F0C4M/QOoP9+0wKXfecAHmEn8L+CtXQT2J7CLXKi5FX2l7itN/RoyHp6uigOxNXLMpAr59a5BZE2vDIMzXiUMGt3rQ7O8u+l30wcyi0sdrbC8qMGBDNOr6i+3yvPTO90N8hkiTJCOrsEItH+IuLIsek+rfXYYvrzQUGVmbdVZXSiKawxpgpptYwqIwkJP8C4qDem9fVsvmwUwvneqKKfdDgh7h18DzR4HU//S+AmKrZnF53WAx6XYFcjWqbsnscEVWZ4nY59aKXgKttfEpl57w=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=scc-lofselectclub-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
